version: 2.1
workflows:
  build-deploy:
    jobs:
     - build:
        filters:
          branches:
            only: master
        context:
          - dockerhub
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 19.03.14
      - checkout
      - run: 
          name: Enable experimental feature
          command: |
            ssh remote-docker \<<EOF
              sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
              sudo systemctl restart docker
              sudo docker info
            EOF
      - run: 
          name: Build and Push to Dockerhub
          command: |
            docker run --rm --privileged linuxkit/binfmt:v0.8
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker context create tobira
            docker buildx create --name build --use tobira --driver-opt network=host
            docker buildx build -t "${DOCKERHUB_USERNAME}/tobira:latest" --platform linux/amd64,linux/arm64,linux/arm/v7 --push .